Updated the Flask API integration- 5

diff --git a/.github/workflows/integration_CI.yml b/.github/workflows/integration_CI.yml
--- a/.github/workflows/integration_CI.yml
+++ b/.github/workflows/integration_CI.yml
@@ -34,7 +34,11 @@ jobs:
       - name: Start Flask App in Background
         run: |
           nohup python app.py > flask.log 2>&1 &
-          sleep 5
+          sleep 10
+
+      - name: Check if Flask is Running
+        run: |
+          curl http://127.0.0.1:5000/info?id=1 || (echo "Flask app failed to start!" && cat flask.log && exit 1)
 
       - name: Install Newman CLI
         run: |
